/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

/**
 *
 * @author erick
 */
public class A_GA extends javax.swing.JFrame {

    /**
     * Creates new form A_GA
     */
    public A_GA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        E_Logo = new javax.swing.JLabel();
        B_MC = new javax.swing.JButton();
        B_CS = new javax.swing.JButton();
        B_RA = new javax.swing.JButton();
        B_CA = new javax.swing.JButton();
        B_EA = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        E_Dialogo = new javax.swing.JLabel();
        E_fondo_azul = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Say Woof!-Administrador-Gestionar Administradores");

        Panel.setBackground(new java.awt.Color(255, 255, 255));
        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        E_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LOGO_3.png"))); // NOI18N
        Panel.add(E_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 100));

        B_MC.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        B_MC.setText("Mi Cuenta");
        Panel.add(B_MC, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 100, 40));

        B_CS.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        B_CS.setText("Cerrar Sesión");
        Panel.add(B_CS, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 110, 40));

        B_RA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Administrador/Agregar_Admin.png"))); // NOI18N
        Panel.add(B_RA, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 160, 100));

        B_CA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Administrador/Credencial.png"))); // NOI18N
        Panel.add(B_CA, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 160, 100));

        B_EA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Administrador/EliminarAdmin.png"))); // NOI18N
        Panel.add(B_EA, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 160, 100));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registrar Administrador");
        Panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 150, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Consultar Administradores");
        Panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Eliminar Administrador");
        Panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, -1, 20));

        jLabel4.setBackground(new java.awt.Color(255, 153, 51));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Administrador/perrito1.png"))); // NOI18N
        Panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 155, 150));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("¿Qué vamos a");
        Panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 140, 40));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("hacer?");
        Panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 120, 40));

        E_Dialogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Administrador/Viñeta2.png"))); // NOI18N
        Panel.add(E_Dialogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 140, 80));

        E_fondo_azul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo_azul_horizontal.png"))); // NOI18N
        Panel.add(E_fondo_azul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(A_GA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(A_GA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(A_GA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(A_GA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new A_GA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_CA;
    private javax.swing.JButton B_CS;
    private javax.swing.JButton B_EA;
    private javax.swing.JButton B_MC;
    private javax.swing.JButton B_RA;
    private javax.swing.JLabel E_Dialogo;
    private javax.swing.JLabel E_Logo;
    private javax.swing.JLabel E_fondo_azul;
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
