/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

/**
 *
 * @author erick
 */
public class Administrador extends javax.swing.JFrame {

    /**
     * Creates new form Administrador
     */
    public Administrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        E_Logo = new javax.swing.JLabel();
        B_MC = new javax.swing.JButton();
        B_CS = new javax.swing.JButton();
        B_GA = new javax.swing.JButton();
        B_GC = new javax.swing.JButton();
        B_GP = new javax.swing.JButton();
        B_GF = new javax.swing.JButton();
        E_Fondoazul = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Say Woof! - Administrador");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        E_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LOGO_3.png"))); // NOI18N
        jPanel1.add(E_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 100));

        B_MC.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        B_MC.setText("Mi Cuenta");
        jPanel1.add(B_MC, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 110, 40));

        B_CS.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        B_CS.setText("Cerrar Sesión");
        jPanel1.add(B_CS, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 120, 40));

        B_GA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Admin.png"))); // NOI18N
        jPanel1.add(B_GA, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 160, 100));

        B_GC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Usuario_icono.png"))); // NOI18N
        jPanel1.add(B_GC, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 160, 100));

        B_GP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/publicacion.png"))); // NOI18N
        B_GP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_GPActionPerformed(evt);
            }
        });
        jPanel1.add(B_GP, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 160, 100));

        B_GF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/foro.png"))); // NOI18N
        jPanel1.add(B_GF, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 160, 100));

        E_Fondoazul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo_azul_horizontal.png"))); // NOI18N
        jPanel1.add(E_Fondoazul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestionar Administradores");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Gestionar Clientes");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Gestionar Publicaciones");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Gestionar Foros");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/perro3.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void B_GPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_GPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_GPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_CS;
    private javax.swing.JButton B_GA;
    private javax.swing.JButton B_GC;
    private javax.swing.JButton B_GF;
    private javax.swing.JButton B_GP;
    private javax.swing.JButton B_MC;
    private javax.swing.JLabel E_Fondoazul;
    private javax.swing.JLabel E_Logo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
