
package Login;

import javax.swing.JOptionPane;

public class LogIn extends javax.swing.JFrame {

    public LogIn() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        Etiqueta_Usuario = new javax.swing.JLabel();
        Etiqueta_Constraseña = new javax.swing.JLabel();
        Tipo_Usuario = new javax.swing.JLabel();
        Caja_Usuario = new javax.swing.JTextField();
        Caja_TUsuario = new javax.swing.JTextField();
        Caja_Contraseña = new javax.swing.JPasswordField();
        Iniciar_Sesion = new javax.swing.JButton();
        Fondo_azul = new javax.swing.JLabel();
        Say_Woof = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Say Woof!");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        setName("Prueba "); // NOI18N
        setResizable(false);

        Panel.setBackground(new java.awt.Color(255, 255, 255));
        Panel.setForeground(new java.awt.Color(255, 255, 255));
        Panel.setPreferredSize(new java.awt.Dimension(750, 500));
        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/Imagenes/LOGO.png"))); // NOI18N
        Panel.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 350, 260));

        Etiqueta_Usuario.setBackground(java.awt.SystemColor.inactiveCaption);
        Etiqueta_Usuario.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Etiqueta_Usuario.setForeground(new java.awt.Color(0, 0, 0));
        Etiqueta_Usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Etiqueta_Usuario.setText("Usuario");
        Panel.add(Etiqueta_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 110, 50));

        Etiqueta_Constraseña.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Etiqueta_Constraseña.setForeground(new java.awt.Color(0, 0, 0));
        Etiqueta_Constraseña.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Etiqueta_Constraseña.setText("Constraseña");
        Panel.add(Etiqueta_Constraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 120, 40));

        Tipo_Usuario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Tipo_Usuario.setForeground(new java.awt.Color(0, 0, 0));
        Tipo_Usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tipo_Usuario.setText("Tipo de Usuario");
        Panel.add(Tipo_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 140, 40));

        Caja_Usuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Panel.add(Caja_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 170, -1));

        Caja_TUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Panel.add(Caja_TUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 140, -1));

        Caja_Contraseña.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Panel.add(Caja_Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 180, -1));

        Iniciar_Sesion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Iniciar_Sesion.setText("Iniciar Sesión");
        Iniciar_Sesion.setOpaque(false);
        Iniciar_Sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Iniciar_SesionActionPerformed(evt);
            }
        });
        Panel.add(Iniciar_Sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 120, 30));

        Fondo_azul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/Imagenes/Fondo_azul.jpg"))); // NOI18N
        Fondo_azul.setText("Usuario");
        Panel.add(Fondo_azul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 500));

        Say_Woof.setBackground(new java.awt.Color(255, 255, 255));
        Say_Woof.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36)); // NOI18N
        Say_Woof.setForeground(new java.awt.Color(0, 94, 188));
        Say_Woof.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Say_Woof.setText("SAY WOOF!");
        Say_Woof.setOpaque(true);
        Panel.add(Say_Woof, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 290, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Iniciar_SesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Iniciar_SesionActionPerformed
        String usuarioCorrecto = "Erick Hazel";
        String usuarioAdmin = "Karina Ramirez";
        String TUadmin = "Administrador";
        String contraseñaAdmin = "5678";
        String TUcorrecto = "Cliente";
        String contraseñaCorrecta = "1234";
        String contraseñaJP = "";
        
      //COMPROBAMOS A LOS TIPOS DE USUARIO
      if(TUcorrecto.equals(Caja_TUsuario.getText())){ //TIPO CLIENTE
          if(usuarioCorrecto.equals(Caja_Usuario.getText())){ //USUARIO CORRECTO
              for(int i = 0; i<Caja_Contraseña.getPassword().length;i++ ){
                    contraseñaJP += Caja_Contraseña.getPassword()[i];
              }
              if(contraseñaCorrecta.equals(contraseñaJP)){ //CONTRASEÑA CORRECTA
                  //CREO VENTANA PARA CLIENTE
                  Ventana_Clientes v1 = new Ventana_Clientes();
                  this.dispose();
                  v1.setVisible(true);
              }
              else{
                  JOptionPane.showMessageDialog(null, "Contraseña incorrecta :'v");
              }
          }
          else{
              JOptionPane.showMessageDialog(null, "Usuario Incorrecto :v");
          }
      }
      else if(TUadmin.equals(Caja_TUsuario.getText())){ //TIPO ADMINISTRADOR
          if(usuarioAdmin.equals(Caja_Usuario.getText())){ // USUARIO CORRECTO
              for(int i = 0; i<Caja_Contraseña.getPassword().length;i++ ){
                    contraseñaJP += Caja_Contraseña.getPassword()[i];
              }
              if(contraseñaAdmin.equals(contraseñaJP)){// CONTRASEÑA CORRECTA
                  //CREO VENTANA PARA ADMIN
                  Ventana_Admin v1 = new Ventana_Admin();
                  this.dispose();
                  v1.setVisible(true);
              }
              else{
                  JOptionPane.showMessageDialog(null, "Contraseña incorrecta :'v");
              }
          }
          else{
              JOptionPane.showMessageDialog(null, "Usuario Incorrecto :v");
          }
      }
      else {
           JOptionPane.showMessageDialog(null, "Tipo de Usuario incorrecto :'v");
      }
    }//GEN-LAST:event_Iniciar_SesionActionPerformed

    /* @param args the command line arguments*/
    public static void main(String args[]) {
        //Set the Nimbus look and feel 
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        // Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Caja_Contraseña;
    private javax.swing.JTextField Caja_TUsuario;
    private javax.swing.JTextField Caja_Usuario;
    private javax.swing.JLabel Etiqueta_Constraseña;
    private javax.swing.JLabel Etiqueta_Usuario;
    private javax.swing.JLabel Fondo_azul;
    private javax.swing.JButton Iniciar_Sesion;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel Say_Woof;
    private javax.swing.JLabel Tipo_Usuario;
    // End of variables declaration//GEN-END:variables
}
