/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

/**
 *
 * @author erick
 */
public class Mi_Cuenta extends javax.swing.JFrame {

    /**
     * Creates new form Mi_Cuenta
     */
    public Mi_Cuenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_MC = new javax.swing.JPanel();
        LogoMC = new javax.swing.JLabel();
        Boton_CS_MC = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Fondo_azulMC = new javax.swing.JLabel();
        Logo_Usuario = new javax.swing.JLabel();
        Caja_Usuario = new javax.swing.JTextField();
        Caja_Correo = new javax.swing.JTextField();
        Boton_ModiInfo = new javax.swing.JButton();
        Huellas = new javax.swing.JLabel();
        Usuario = new javax.swing.JLabel();
        Correo_electronico = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mi cuenta");
        setResizable(false);

        panel_MC.setBackground(new java.awt.Color(255, 255, 255));
        panel_MC.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panel_MC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogoMC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/Imagenes/LOGO2.png"))); // NOI18N
        panel_MC.add(LogoMC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Boton_CS_MC.setBackground(new java.awt.Color(255, 255, 255));
        Boton_CS_MC.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Boton_CS_MC.setText("Cerrar Sesión");
        Boton_CS_MC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_CS_MCActionPerformed(evt);
            }
        });
        panel_MC.add(Boton_CS_MC, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 30, 160, 40));

        jButton2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panel_MC.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, 160, 40));

        Fondo_azulMC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/Imagenes/Fondo_azul_horizontal.jpg"))); // NOI18N
        Fondo_azulMC.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panel_MC.add(Fondo_azulMC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2140, -1));

        Logo_Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/Imagenes/dog-seatting.png"))); // NOI18N
        panel_MC.add(Logo_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 420, 320));
        panel_MC.add(Caja_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 300, 310, 40));
        panel_MC.add(Caja_Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 400, 310, 40));

        Boton_ModiInfo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Boton_ModiInfo.setText("Modificar Información");
        panel_MC.add(Boton_ModiInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, 280, 50));

        Huellas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/Imagenes/Huellas_claras.png"))); // NOI18N
        panel_MC.add(Huellas, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 150, 300, 480));

        Usuario.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Usuario.setForeground(new java.awt.Color(0, 0, 0));
        Usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Usuario.setText("Usuario");
        panel_MC.add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, 110, 40));

        Correo_electronico.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Correo_electronico.setForeground(new java.awt.Color(0, 0, 0));
        Correo_electronico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Correo_electronico.setText("Correo electrónico");
        panel_MC.add(Correo_electronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, 180, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_MC, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_MC, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_CS_MCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_CS_MCActionPerformed
        // TODO add your handling code here:
        LogIn v1 = new LogIn();
        this.dispose();
        v1.setVisible(true);
    }//GEN-LAST:event_Boton_CS_MCActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Ventana_Clientes vc = new Ventana_Clientes();
        this.dispose();
        vc.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mi_Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mi_Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mi_Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mi_Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mi_Cuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_CS_MC;
    private javax.swing.JButton Boton_ModiInfo;
    private javax.swing.JTextField Caja_Correo;
    private javax.swing.JTextField Caja_Usuario;
    private javax.swing.JLabel Correo_electronico;
    private javax.swing.JLabel Fondo_azulMC;
    private javax.swing.JLabel Huellas;
    private javax.swing.JLabel LogoMC;
    private javax.swing.JLabel Logo_Usuario;
    private javax.swing.JLabel Usuario;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel panel_MC;
    // End of variables declaration//GEN-END:variables
}
