//PAQUETES
package Login;

//CLASE VENTANA

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JOptionPane;

public class Ventana_Clientes extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Clientes
     */
    public Ventana_Clientes() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel1_VC = new javax.swing.JPanel();
        Cerrar_Sesion = new javax.swing.JButton();
        Mi_Cuenta = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();
        Boton_Foro = new javax.swing.JButton();
        Categorias = new javax.swing.JComboBox();
        Imagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana Clientes");
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setName("Ventana_Clientes"); // NOI18N
        setResizable(false);

        Panel1_VC.setBackground(new java.awt.Color(255, 255, 255));
        Panel1_VC.setForeground(new java.awt.Color(255, 255, 255));
        Panel1_VC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cerrar_Sesion.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Cerrar_Sesion.setText("Cerrar Sesión");
        Cerrar_Sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cerrar_SesionActionPerformed(evt);
            }
        });
        Panel1_VC.add(Cerrar_Sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 40, 140, 50));

        Mi_Cuenta.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Mi_Cuenta.setText("Mi Cuenta");
        Mi_Cuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mi_CuentaActionPerformed(evt);
            }
        });
        Panel1_VC.add(Mi_Cuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 40, 130, 50));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/Imagenes/LOGO2.png"))); // NOI18N
        Panel1_VC.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 200));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/Imagenes/Fondo_azul_horizontal.jpg"))); // NOI18N
        Panel1_VC.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Boton_Foro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Boton_Foro.setText("Participar en Foros");
        Boton_Foro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_ForoActionPerformed(evt);
            }
        });
        Panel1_VC.add(Boton_Foro, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 170, 30));

        Categorias.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Categorias", "Alimento", "Adiestramiento", "Comportamiento", "Juguetes", "Salud" }));
        Categorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoriasActionPerformed(evt);
            }
        });
        Panel1_VC.add(Categorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 230, 30));

        Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/Imagenes/klipartz.com.png"))); // NOI18N
        Panel1_VC.add(Imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, 600, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1_VC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1_VC, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_ForoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_ForoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_ForoActionPerformed

    private void Cerrar_SesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cerrar_SesionActionPerformed
        this.dispose(); 
        LogIn v1 = new LogIn();
        
        v1.setVisible(true);
        
    }//GEN-LAST:event_Cerrar_SesionActionPerformed

    private void Mi_CuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mi_CuentaActionPerformed
        // TODO add your handling code here:
        Mi_Cuenta m1 = new Mi_Cuenta();
        this.dispose();
        m1.setVisible(true);
    }//GEN-LAST:event_Mi_CuentaActionPerformed

    private void CategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoriasActionPerformed
        // TODO add your handling code here:
        String opcion = (String) Categorias.getSelectedItem();
        /*if (opcion == "Alimento"){
            JOptionPane.showMessageDialog(null,"HOLA XD");
        }*/
        switch(opcion){
            case "Alimento":
                JOptionPane.showMessageDialog(null,"HOLA XD");
                break;
            case "Adiestramiento":
                JOptionPane.showMessageDialog(null,"adiestramiento XD");
                break;
            case "Comportamiento":
                JOptionPane.showMessageDialog(null,"Comportamiento XD");
                break;
            case "Juguetes":
                JOptionPane.showMessageDialog(null,"Juguetes XD");
                break;
            case "Salud":
                JOptionPane.showMessageDialog(null,"Salud XD");
                break;
            
        }
  
    }//GEN-LAST:event_CategoriasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Clientes().setVisible(true);
            }
        });
    }

    //DECLARACION DE VARIABLES
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Foro;
    private javax.swing.JComboBox Categorias;
    private javax.swing.JButton Cerrar_Sesion;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Imagen;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton Mi_Cuenta;
    private javax.swing.JPanel Panel1_VC;
    // End of variables declaration//GEN-END:variables
}
