/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import javax.swing.JOptionPane;

/**
 *
 * @author erick
 */
public class Ventana_Admin extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Admin
     */
    public Ventana_Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_VAdmin = new javax.swing.JPanel();
        Cerrar_SsesionVA = new javax.swing.JButton();
        MiCuenta_VA = new javax.swing.JButton();
        Logo_VA = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();
        Gestionar = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana Administradores");
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setName("Ventana_Admin"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 650));

        Panel_VAdmin.setBackground(new java.awt.Color(255, 255, 255));
        Panel_VAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cerrar_SsesionVA.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Cerrar_SsesionVA.setText("Cerrar Sesión");
        Cerrar_SsesionVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cerrar_SsesionVAActionPerformed(evt);
            }
        });
        Panel_VAdmin.add(Cerrar_SsesionVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 30, 140, 50));

        MiCuenta_VA.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        MiCuenta_VA.setText("Mi Cuenta");
        MiCuenta_VA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiCuenta_VAActionPerformed(evt);
            }
        });
        Panel_VAdmin.add(MiCuenta_VA, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 30, 140, 50));

        Logo_VA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/Imagenes/LOGO2.png"))); // NOI18N
        Panel_VAdmin.add(Logo_VA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/Imagenes/Fondo_azul_horizontal.jpg"))); // NOI18N
        Fondo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Panel_VAdmin.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 200));
        Fondo.getAccessibleContext().setAccessibleDescription("");

        Gestionar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gestionar Administradores", "Gestionar Clientes", "Gestionar Foros", "Gestionar Modulo de informacion", " " }));
        Gestionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionarActionPerformed(evt);
            }
        });
        Panel_VAdmin.add(Gestionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 280, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/Imagenes/perro 2.png"))); // NOI18N
        Panel_VAdmin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 300, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_VAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_VAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Cerrar_SsesionVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cerrar_SsesionVAActionPerformed
        // TODO add your handling code here:
        this.dispose(); 
        LogIn v1 = new LogIn();
        v1.setVisible(true);
    }//GEN-LAST:event_Cerrar_SsesionVAActionPerformed

    private void MiCuenta_VAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiCuenta_VAActionPerformed
        // TODO add your handling code here:
        Mi_Cuenta m1 = new Mi_Cuenta();
        this.dispose();
        m1.setVisible(true);
    }//GEN-LAST:event_MiCuenta_VAActionPerformed

    private void GestionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionarActionPerformed
        // TODO add your handling code here:
        String opcion = (String) Gestionar.getSelectedItem();
        /*if (opcion == "Alimento"){
            JOptionPane.showMessageDialog(null,"HOLA XD");
        }*/
        switch(opcion){
            case "Gestionar Administradores":
                JOptionPane.showMessageDialog(null,"HOLA XD");
                break;
            case "Gestionar Clientes":
                JOptionPane.showMessageDialog(null,"adiestramiento XD");
                break;
            case "Gestionar Modulo de informacion":
                JOptionPane.showMessageDialog(null,"Comportamiento XD");
                break;
            case "Gestionar foros":
                JOptionPane.showMessageDialog(null,"Juguetes XD");
                break;  
        }
  
    }//GEN-LAST:event_GestionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cerrar_SsesionVA;
    private javax.swing.JLabel Fondo;
    private javax.swing.JComboBox<String> Gestionar;
    private javax.swing.JLabel Logo_VA;
    private javax.swing.JButton MiCuenta_VA;
    private javax.swing.JPanel Panel_VAdmin;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
